sonar.projectKey=parcial-frontend
sonar.projectName=Parcial Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_747bf42db2abc3d5229dc74b82e38610f83197ae
sonar.javascript.node.maxspace=4096
sonar.scanner.skipJreProvisioning=true
sonar.typescript.tsconfigPath=tsconfig.json