sonar.projectKey=parcial-backend
sonar.projectName=Parcial Backend
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**,**/venv/**,**/.venv/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqa_3bf98c09d4d32641fe8af3556078d2e423af5019
sonar.python.version=3