server {
    listen 80;
    server_name amarillo.si-umng.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name amarillo.si-umng.com;

    ssl_certificate     /etc/letsencrypt/live/amarillo.si-umng.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/amarillo.si-umng.com/privkey.pem;

    # Headers de seguridad
    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    root /var/www/alcaldia/dist/alcaldia-frontend;
    index index.html;

    # Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al backend — el browser nunca llama directo a :8000
    location /api/ {
        proxy_pass http://34.196.57.27:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
